# Generated by Django 4.2 on 2026-01-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='省份名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.province', verbose_name='所属省份')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='景点名称')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='详细地址')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='评分')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='票价')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='图片链接')),
                ('description', models.TextField(blank=True, verbose_name='景点描述')),
                ('open_time', models.CharField(blank=True, max_length=200, verbose_name='开放时间')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='景区等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'ordering': ['-comment_count'],
            },
        ),
    ]
